name: Process Subdomain Requests

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Subdomain Processor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node index.js
